name: Build, Push Docker Image and Apply Terraform

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    environment: deploy
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ejercicio
      IMAGE_TAG: latest
      DOCKER_HUB_USERNAME: scarreiraaws

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $IMAGE_NAME:$IMAGE_TAG ./app

    - name: Tag Docker image for remote
      run: |
        docker tag $IMAGE_NAME:$IMAGE_TAG $DOCKER_HUB_USERNAME:$IMAGE_TAG

    - name: Push Docker image to remote
      run: |
        docker push $DOCKER_HUB_USERNAME:$IMAGE_TAG

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: infra
      run: terraform init

    - name: Terraform Apply
      working-directory: infra
      run: terraform apply -auto-approve
